### PR TITLE
new change in css styling

### PR DESCRIPTION
**Pull request by zakim2307**
changes

### CODE REVIEW

**Comment by zakim2307** [comment]
Hi sir please you can merge this request just a little small css change,

**Comment by StanislavStadnyk** [comment]
> Hi sir please you can merge this request just a little small css change,

Hi I didn't get the changes for `package-lock.json`. Could you explain please?

**Comment by StanislavStadnyk** [comment]
> > Hi sir please you can merge this request just a little small css change,
> 
> Hi I didn't get the changes for `package-lock.json`. Could you explain please?

I've just updated my REPO

**Comment by StanislavStadnyk** [comment]
It has been fixed on my side

**Pull request closed without merging**
